name: Build and Push
on:
  push:
    branches:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

# env:
  ## SET_NAME - overrides the docker image name (name is repo name with docker- prefix stripped)

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
    steps:
      - id: set
        run: |
          # Computed org/repo name, docker- prefix is stripped off
          export DEFAULT_IMAGE=$(echo -n '${{ github.event.organization.login }}/'; echo '${{ github.event.repository.name }}' | sed 's/^docker-//' | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=image::${SET_NAME:-$DEFAULT_IMAGE}"

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [pre]

    strategy:
      matrix:
        flavor: [default, gcloud, aws]
        include:
          - flavor: default
            installs: basic python nodejs
          - flavor: gcloud
            installs: basic python nodejs google-cloud-sdk
            suffix: -gcloud
          - flavor: aws
            installs: basic python nodejs aws
            suffix: -aws

    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: dysnix/Dockerfile
      -
        uses: dysnix/find-latest-tag@v1
        id: findLatest
        with:
          regex: '^v\d'
          compared-to-tag: ${{ github.ref }}
          repository: ${{ github.repository }}
      -
        uses: actions/github-script@v5
        id: set
        with:
          script: |
            if ( '${{ steps.findLatest.outputs.older }}' === 'false' ) {
              // Specify latest or flavor
              core.setOutput('latestFlavor',
                '${{ matrix.flavor }}' !== 'default' ? '${{ matrix.flavor }}' : 'latest'
              );
            }
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ needs.pre.outputs.image }}
          flavor: |
            latest=false
            suffix=${{ matrix.suffix }}
          ## Note: we don't tag any semver, since for github actions runner it's unnecessary (latest is required)
          tags: |
            type=raw,value=${{ steps.set.outputs.latestFlavor }},suffix=
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.flavor }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.flavor }}
      -
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ steps.meta.outputs.tags != '' }}
          file: dysnix/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            VIRTUAL_ENV_INSTALLS=${{ matrix.installs }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
