name: Check RunnerNewVersion
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    name: Publish new tag
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - uses: dysnix/find-latest-tag@v1
      id: upstream
      with:
        regex: v2\.[0-9]+\.[0-9]+$
        repository: actions/runner

    - uses: dysnix/find-latest-tag@v1
      id: latest
      with:
        compared-to-tag: ${{ steps.upstream.outputs.tag }}
        regex: v2\.[0-9]+\.[0-9]+$
        repository: ${{ github.repository }}

    - name: Publish new release
      uses: ncipollo/release-action@v1
      if: steps.latest.outputs.newer == 'true' || steps.latest.outputs.tag == ''
      with:
        body: |
          new upstream release ${{ steps.upstream.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.upstream.outputs.tag }}
        commit: master
